from app.tools.check_refund_eligiblity import check_refund_eligibility
from app.tools.get_order_status import get_order_status
from app.tools.lookup_customer import lookup_customer
from app.tools.search_knowledge_base import search_knowledge_base

tools = [check_refund_eligibility,get_order_status,lookup_customer,search_knowledge_base]